### ISSUE TITLE
Breaks firebug - Fx3 on Mac

### ISSUE THREAD

**Issue by jhansche** [binaryage/firequery#1]
Firebug 1.3.3 on Firefox 3.0.11 on Mac OS X (10.5.7)

The Firebug icon is gray (disabled) in bottom right corner, and clicking the icon, using the Tools > Firebug menu, or selecting "Inspect Element" from the context menu, all do nothing.

**Comment by jhansche** [comment]
My mistake, I now see the "Firebug 1.4" requirement.  It should refuse to install on Firebug <1.4.

**Comment by darwin** [comment]
I should investigate how it behaves with FB1.3, but I didn't take time to do it. Take this as a alpha release, it definitely needs more polishing.

**Comment by darwin** [comment]
FireQuery 0.4 works with Firebug 1.3
