### ISSUE TITLE
metadata is output incorrectly on console

### ISSUE THREAD

**Issue by rvock** [binaryage/firequery#10]
I have an element with metadata and the jQuery metadata plugin.
The code of the element with metadata is: 
&lt;li class="{id: 678}"&gt;

When I enter $('li:first').metadata() in the firebug console I get the following output:
{ id=undefined }

Without firequery I get
{ id=678 }

(And that's what I would expect and want to see :))

**Comment by rvock** [comment]
It's not only metadata, but all objects.
enter in console:
var a = {foo: 'bar', baz: 5};
a
{ asdf=undefined muh=undefined }

**Comment by darwin** [comment]
do not force JSON object notation, Firebug authors did some changes towards it, which broke my original code (closed by ae9a09c6dc40b695665e57393fda3f0a5d7f341c)
