### ISSUE TITLE
Doesn't work with FB 1.6X.16+

### ISSUE THREAD

**Issue by TrejGun** [binaryage/firequery#14]
I think this becouse 1.6X.16 provides support of FF4

**Comment by darwin** [comment]
fixed in v0.8
http://github.com/darwin/firequery/tree/v0.8

**Comment by TrejGun** [comment]
thx a lot

**Comment by TrejGun** [comment]
will you please build it?

**Comment by darwin** [comment]
https://addons.mozilla.org/en-US/firefox/addon/12632/versions/

**Comment by TrejGun** [comment]
works great on 1.7X.0a4
