### ISSUE TITLE
Not marked compatible with Firefox 5

### ISSUE THREAD

**Issue by lukemaurer** [binaryage/firequery#20]
Can't run FireQuery in Firefox 5; the Add-ons Manager says “FireQuery is incompatible with Firefox 5.0.”

**Comment by darwin** [comment]
yes, I've bumped the version limit but FireQuery seems to be broken with latest Firebug 1.8

so far I haven't been able to fix the problem, because latest chromebug is broken, will do next trial during weekend (hopefully)

**Comment by darwin** [comment]
1.0 should be fine, at least I fixed bugs on my machine with the latest Firebug 1.8
