### ISSUE TITLE
term-ansicolor version - 1.0.5 being ignored by rake?

### ISSUE THREAD

**Issue by aaronmcadam** [binaryage/firequery#21]
Hi there, when I run rake, I get the message: Run "gem install term-ansicolor" even though I've installed it already?

**Comment by darwin** [comment]
comment out begin - rescue block in that rake script and rake --trace will tell you what is the trouble

**Comment by aaronmcadam** [comment]
Hiya I get "no such file to load -- term/term-ansicolor" is there some way to check where the gems are installed?

**Comment by darwin** [comment]
your gem installation must be broken somehow, I'm sorry I cannot help

you may also fork the project and strip out term-ansicolor dependency from the rake, I will probably accept it

**Comment by darwin** [comment]
I have switched rake to colored gem. This should fix your issues.

**Comment by aaronmcadam** [comment]
Thanks for getting back, completely forgot about this issue :D
