### ISSUE TITLE
Support jQuery 1.7

### ISSUE THREAD

**Issue by davemo** [binaryage/firequery#24]
Currently the HTML pane in Firebug 1.8.4 does not display any of the FireQuery dynamic binding data when using the latest jQuery release (1.7). This was really useful, any chance we could get an update? If not I'll take a peek at updating this with a pull request later tonight.

**Comment by darwin** [comment]
jQuery 1.7 changed the way how $(...).data() works, it does not expose internal jQuery data structures anymore (for example "events" structure)

**Comment by davemo** [comment]
So does this mean it's not possible to have the same functionality in FireQuery with jQuery 1.7?

**Comment by aliaksej** [comment]
Today I spent 2 hours to fix this issue for latest jQuery 1.7.1
In 1.7 version events are removed from $(elem).data() function

To get events list bound to function, we need to get data directly

``` javascript
var el = jQuery('\<span\>').click(function () {123}), data, events;
data = el.data();
if (parseFloat(jQuery.fn.jquery) >= 1.7 && !data.events) {
   events = el.data('events');
   if (events) {
       data = $.extend({}, data, {events: events});
   }
}

console.log(data); // getting data with events if events are bound
```

please fix!!! I really like your extension!!!

thanks a lot :)

**Comment by darwin** [comment]
I believe you may just call $._data(el) instead to get the old behavior

**Comment by darwin** [comment]
I have reimplemented it in v1.1 to show all internal data, not only events. It required more rewriting, but I believe it is more robust solution.

Anyway thanks for your contribution.

**Comment by sphinxz** [comment]
yes please fix it,
