### ISSUE TITLE
xxx is undefined issue in jQuery

### ISSUE THREAD

**Issue by jmav** [binaryage/firequery#27]
Environment:
Win 7 64bit
FF 9.0.1 Eng.
Firequery 1.1

test web address:
http://jqueryui.com/demos/draggable/

When moving div in sample, following errors appears:
a(this).data("draggable") is undefined

Similar issues appears also in:
http://layout.jquery-dev.net/demos/complex.html

**Comment by darwin** [comment]
dupe of issue #28
