### ISSUE TITLE
Breaks jQuery data()

### ISSUE THREAD

**Issue by itechnology** [binaryage/firequery#28]
When "show internal jQuery data" is checked, returning of data() in jQuery breaks (on whole site)

```
jQuery("body").data("foo", 1);

jQuery("body").data("foo");
     returns undefined
```

**Comment by ashclarke** [comment]
It seems that `.data("key", value)` adds a data property inside the data property of an element.

![FireQuery Data Issue](http://www.ashclarke.com/blog/wp-content/uploads/2012/02/data-issue.png)(http://www.ashclarke.com/blog/wp-content/uploads/2012/02/data-issue.png)

Without ShowInternalData enabled, I can't see events or data properties on elements. When it's on the above happens.

Any ideas?

**Comment by CzBiX** [comment]
yep, it's breaks my scripts run normal.

**Comment by sprintstar** [comment]
Not sure its related, but I get a similar problem.  With "show internal jQuery data" checked, the following fails (alert displays undefined):

``` javascript
$(function () { 
   $('body').data('hello', 'world'); 
   setTimeout(function () { 
      alert($('body').data('hello')); 
    }, 0); 
});
```
