### ISSUE TITLE
reference to undefined property window.jQuery http://localhost/projects/framed.htm Line 0

### ISSUE THREAD

**Issue by Jurgster** [binaryage/firequery#3]
thought there would at least be a toggle switch for jQuery so that this error:
reference to undefined property window.jQuery
http://localhost/projects/Pettys/rebeccas_dev/framed.htm
Line 0

would not be repetitively given till I disrupt the loop with clicking on the jQuery button.

**Comment by darwin** [comment]
I don't understand what actions did you take to reproduce the bug.

please rephrase your report and give me a link to problematic file

**Comment by Jurgster** [comment]
Oh I seem to have commented privately.

Unfortunately a link will not be possible, as you may have noticed it is localhost. However I could give a tip in that I was doing nothing jQuery orientated. To say the least I am new to the subject jQuery and I had installed the add-on as a preparation to taking the subject up. I am very knowledge hungry and as I had said I thought a disable function like all add-ons by firebug would be available.

I do not have jquery installed, just firequery. As jquery is not installed/ref. there will always be a error call:
reference to undefined property window.jQuery
but at the same time there is no means of disabling firequery from within firebug.
As to that, I then have to open FF add-ons window to disable the add-on firequery and restart FF.
It would be nice to have a toggle within firebug to disable firequery when not required to avoid unnecessary jquery error feedbacks like the one I posted.

**Comment by darwin** [comment]
Ah, ok, now I see. There are also internets not using jquery ;-)

Thanks for reporting. Will fix this in next release.

**Comment by darwin** [comment]
please test it with v0.4, I was unable to reproduce it
