### ISSUE TITLE
Option to force injection of latest jquery

### ISSUE THREAD

**Issue by jgutix** [binaryage/firequery#30]
For the jquerify button, I would like to be able to force injection of latest jquery version, currently jquerify detectss if jquery is loaded and shows the version, but for sites with old version I would like to inject it a newer version, this could be useful for testing the behaviour with new versions even without modify the code.

**Comment by darwin** [comment]
This is not technically possible. jQuerify injects jQuery late in the page lifecycle. All document load code was executed for example. It is not possible to change jQuery version under live code depending on jQuery after load.
