### ISSUE TITLE
"Exposing chrome JS objects to content without __exposedProps__ is insecure and deprecated."

### ISSUE THREAD

**Issue by sasquach** [binaryage/firequery#31]
In firefox 15 i get following error in firebug on some pages with jquery (your test page including - http://firequery.binaryage.com/test/):

"Exposing chrome JS objects to content without **exposedProps** is insecure and deprecated. See https://developer.mozilla.org/en/XPConnect_wrappers for more information.
http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js
Line 2"

Looks like there is a post about this on mozilla blog: https://blog.mozilla.org/addons/2012/08/20/exposing-objects-to-content-safely/

I hope you can fix it soon.

**Comment by caseman72** [comment]
+1

**Comment by darwin** [comment]
experimental fix: 64481d3472aed83228aefa7ef6993377a826182b

it works for my test page, but it is ugly - I hope I will look into that more early next week

**Comment by TheSneak** [comment]
+1

**Comment by darwin** [comment]
finally fixed in v1.3: http://firequery.binaryage.com/#changelog
