### ISSUE TITLE
Infinite recursion crash with Firefox 16.0.2 and Firebug 1.10.5

### ISSUE THREAD

**Issue by scalvert** [binaryage/firequery#32]
After the latest upgrade to Firebug 1.10.5 using Firefox 16.0.2 on Windows 8 64bit, every time I try to use the element inspector tool in Firebug I get an infinite recursion crash. Specifically, the Firebug console is spammed with a ton of GET requests, seemingly to all my scripts on my page. Additionally, it seems that each script on the page has jQuery's GET cache buster appended to the end of the URL, i.e. _=12345566. 

Disabling FireQuery resolves the issue.

**Comment by vkartaviy** [comment]
I have the similar issue on Mac... :cry: 

Firefox: 23.0.1
Firebug: 1.12.1
Firequery: 1.4.1 
jQuery: 2.0.3
