### ISSUE TITLE
Attached events are not displayed

### ISSUE THREAD

**Issue by thany** [binaryage/firequery#33]
Events are data, too, and it would be extremely useful to see events attached just like data... Here's a jsfiddle that shows how events are not displayed by FireQuery:
http://jsfiddle.net/FRZwp/

I'm testing this in Windows 7, Firefox 17.0.1, FireBug 1.11.0 and FireQuery 1.3. However this problem/shortcoming has been around for a while (honestly I can't even remember if it has worked, so I don't know if it's a bug or a feature request :P)

Can this be fixed/added?

**Comment by agentbishop** [comment]
I have the same issue.  However, on one of my workstations it works, and on another it does NOT.  Both are running the same versions (Windows 7, Firefox 17.0.1, FireBug 1.11.0 and FireQuery 1.3).

On the instance that does not work, I do see the values of "data-" attributes in the FireBug pane, injected by FireQuery, so it would seem that some of FireQuery is working.

I have also tested this with the jsfiddle that the user "thany" posted (http://jsfiddle.net/FRZwp/).  Same issue.  I have included two screenshots, one NOT working and one working, respectively.

![BadTest](https://f.cloud.github.com/assets/3190534/44725/cadc754c-56ed-11e2-899c-620c6d7f14e1.png)
![GoodTest](https://f.cloud.github.com/assets/3190534/44726/f04e6c22-56ed-11e2-98b1-712a4e62672a.png)

**Comment by darwin** [comment]
please see http://firequery.binaryage.com/#faq - the second question: "How can I show internal jQuery data (e.g. 'events')?"

**Comment by agentbishop** [comment]
darwin : Bingo!  That worked.  The "other" workstation did not have the "show internal jQuery data" option turned on. 

Thank for you for the information, the quick response, and a great development tool.

**Comment by darwin** [comment]
Good! Closing.
