### ISSUE TITLE
Eyecon Datepicker invalid date created

### ISSUE THREAD

**Issue by KevinTriplett** [binaryage/firequery#5]
Issue can be seen on this page: http://eyecon.ro/datepicker/#about

This is not the "standard" jQuery datepicker -- it's a nice plugin that allows selecting a range of dates. Picking a date results in an Invalid date -- something to do with the Date class (which this plugin extends, so it may be some interaction between the plugin and FireQuery).

**Comment by darwin** [comment]
I consider this fixed as of v0.5
