### ISSUE TITLE
Breaks inspector in Firebug 1.5 beta 5

### ISSUE THREAD

**Issue by petersendidit** [binaryage/firequery#7]
If you have Firebug 1.5 beta 5 installed and FireQuery 0.3 installed the inspector tool stops working.  You can use the tool and the blue outline shows up on the page but the html tab doesn't update and show you the selected element.  Disabling FireQuery fixes the problem.

**Comment by darwin** [comment]
get latest from github, it should be FB1.5 compatible, just didn't have time to do proper release.

I want to test it properly with final FB1.5 and FF3.5 and 3.6
